//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class IntQuoteTran
{
    public int QuoteTransID { get; set; }
    public int QuoteID { get; set; }
    public int ItemID { get; set; }
    public Nullable<int> ConfigItemInstanceID { get; set; }
    public string ts_Item { get; set; }
    public string ts_QuoteDescription { get; set; }
    public decimal ts_Price { get; set; }
    public decimal ts_Cost { get; set; }
    public bool IsBaseAssembly { get; set; }
    public int Qty { get; set; }
    public bool IsAcc { get; set; }
}

public partial class tItem
{
    public string ItemID { get; set; }
    public string Item { get; set; }
    public string ItemCatID { get; set; }
    public Nullable<decimal> Cost { get; set; }
    public Nullable<bool> Show { get; set; }
    public Nullable<bool> IsAssembly { get; set; }
    public string QuoteDesc { get; set; }
    public Nullable<decimal> MSRP { get; set; }
    public int IsModel { get; set; }
    public Nullable<bool> UseMSRP { get; set; }
    public int StateID { get; set; }
    public string Specs { get; set; }
    public string FID_ItemImage { get; set; }
    public string IMA_ItemID { get; set; }
}

public partial class VW_OMCQuickShip
{
    public string OrderLineID { get; set; }
    public string OrderLineOrderID { get; set; }
    public string OrderLineParentLineID { get; set; }
    public Nullable<double> OrderLineUnitPriceWithVAT { get; set; }
    public string OrderLineProductID { get; set; }
    public string OrderLineProductName { get; set; }
}

public partial class VW_OMCWebItem
{
    public string ItemID { get; set; }
    public string ItemName { get; set; }
    public string ComponentType { get; set; }
    public decimal AccountingCost { get; set; }
    public decimal StandardCost { get; set; }
    public string QEItemID { get; set; }
}

public partial class VW_OMCWebQuote
{
    public int QuoteID { get; set; }
    public string cudID { get; set; }
    public string OrderCustomerCompany { get; set; }
    public string CudXML { get; set; }
    public string OrderLineProductID { get; set; }
}
